- apps/sandbox/src/project.ts
- apps/sandbox/src/types/module.ts
- apps/workshop/projects/Adax/modules/AdaxLiquidity.ts
- **Adax**:
- **[Project Website](https://dex.adax.pro/)**:
- **Description**: https://adax.gitbook.io/adax
> fix: update adax price strategy

- apps/workshop/projects/WhiteWhale/helpers/index.ts
- **WhiteWhale**:
1. URL not allowed in protocols. replaced by join.
> bugfix: url not allowed in protocols

- apps/sandbox/src/project.ts
- apps/sandbox/src/types/module.ts
- apps/workshop/projects/WhiteWhale/modules/WhiteWhaleLiquidity.ts
* TotalSupply and reserves have to be normalized before using it in fetchPools
> fix(sandbox): total supply value should be normalized

- apps/workshop/projects/AllbridgeCore/abis/pool-abi.json
- apps/workshop/projects/AllbridgeCore/helpers/chain.ts
- apps/workshop/projects/AllbridgeCore/helpers/token-info.ts
- apps/workshop/projects/AllbridgeCore/index.ts
- apps/workshop/projects/AllbridgeCore/modules/AllbridgePool.ts
- apps/workshop/projects/AllbridgeCore/tests/AllbridgeCore.spec.ts
- **Project Name**: Allbridge Core
- **Project Website**: https://core.allbridge.io/
- **Description**:  Allbridge Core enables the transfer of value between blockchains by offering cross-chain swaps of native stablecoins. Being messaging protocol agnostic, Allbridge Core connects a variety of EVM and non-EVM networks.
- **Logo**: https://drive.google.com/file/d/15LjVsIIPKc8HcT9oydn9ZgarIKCs5LT2/view
> Allbridge. Fixed build issues

- apps/sandbox/src/types/module.ts
- apps/workshop/projects/Perp88/modules/PLPStaking.ts
> fix(perp88): reserve value

- apps/workshop/projects/CroSwap/abis/farms.abi.json
- apps/workshop/projects/CroSwap/abis/pair.abi.json
- apps/workshop/projects/CroSwap/helpers/const.ts
- apps/workshop/projects/CroSwap/helpers/gql.ts
- apps/workshop/projects/CroSwap/helpers/types.ts
- apps/workshop/projects/CroSwap/helpers/util.ts
- apps/workshop/projects/CroSwap/index.ts
- apps/workshop/projects/CroSwap/modules/CroSwap.ts
- apps/workshop/projects/CroSwap/tests/project.spec.ts
- **Project Name**: CroSwap
- **Project Website**: https://croswap.com/
- **Description**: A DEX & Yield farm on the Cronos network
> Integration with CroSwap 

- packages/testing/src/createMockContext.ts
- packages/testing/src/createTestProject.ts
- **Description**: ethers test mock improvements
> test(mocks): improve ethers mocks for testing utils

- apps/workshop/projects/SymbiosisFinance/modules/veSIS.ts
- apps/workshop/projects/SymbiosisFinance/tests/veSIS.spec.ts
> feat: added unlockTime prop to user's position object

- apps/workshop/projects/Perp88/modules/PLPStaking.ts
- apps/workshop/projects/Perp88/tests/PLPStaking.spec.ts
> fix: underlying asset

- apps/workshop/projects/Bolide/helpers/provider.ts
- apps/workshop/projects/Bolide/modules/DepositPools.ts
- apps/workshop/projects/Bolide/modules/FarmingPools.ts
- apps/workshop/projects/Bolide/modules/StakingPools.ts
> fix(bolide): logs added to API call

- package.json
> ci: prettier fix

- apps/sandbox/src/types/module.ts
- apps/workshop/package.json
- apps/workshop/projects/AuraFinance/modules/LockAuraClaimable.ts
- package.json
- AuraFinance: fix feature type for claimable module
- Prettier: try to fix the problem with a different config for lint-staged and CI check
> fix(workshop,aurafinance): change claimable type

- apps/workshop/projects/CroSwap/helpers/util.ts
- apps/workshop/projects/CroSwap/modules/CroSwap.ts
- apps/workshop/projects/CroSwap/tests/project.spec.ts
Made requested changes and fixes.
> fix(CroSwap): underlying assets & user positions

- apps/workshop/projects/SymbiosisFinance/helpers/api.ts
- apps/workshop/projects/SymbiosisFinance/helpers/config.ts
- apps/workshop/projects/SymbiosisFinance/helpers/constants.ts
- apps/workshop/projects/SymbiosisFinance/helpers/utils.ts
- apps/workshop/projects/SymbiosisFinance/index.ts
- apps/workshop/projects/SymbiosisFinance/modules/pools.ts
- apps/workshop/projects/SymbiosisFinance/modules/veSIS.ts
- apps/workshop/projects/SymbiosisFinance/tests/veSIS.spec.ts
> feat: add pool modules to symbiosis finance

- apps/workshop/projects/Bolide/modules/FarmingPools.ts
- apps/workshop/projects/Bolide/modules/StakingPools.ts
Rewards amount calculation was fixed for Farming and Staking pools
> fix(bolide): farming rewards amount

- apps/workshop/projects/SymbiosisFinance/helpers/config.ts
- apps/workshop/projects/SymbiosisFinance/index.ts
> feat: symbiosis adds kava-evm pools

- apps/workshop/projects/SymbiosisFinance/helpers/config.ts
- apps/workshop/projects/SymbiosisFinance/helpers/constants.ts
- apps/workshop/projects/SymbiosisFinance/helpers/utils.ts
- apps/workshop/projects/SymbiosisFinance/index.ts
- apps/workshop/projects/SymbiosisFinance/modules/veSIS.ts
- apps/workshop/projects/SymbiosisFinance/tests/veSIS.spec.ts
> feat: symbiosis adds vesis on bnb chain

- README.md
- apps/sandbox/src/types/module.ts
> feat: renamed POS Staking to dPOS Staking

- apps/workshop/projects/SymbiosisFinance/abis/IPair.json
- apps/workshop/projects/SymbiosisFinance/abis/masterChef.json
- apps/workshop/projects/SymbiosisFinance/helpers/config.ts
- apps/workshop/projects/SymbiosisFinance/helpers/utils.ts
- apps/workshop/projects/SymbiosisFinance/index.ts
- apps/workshop/projects/SymbiosisFinance/modules/lpFarm.ts
- apps/workshop/projects/SymbiosisFinance/modules/veSIS.ts
> feat: symbiosis adds lp farm on ethereum, bnb, arbitrum

- .github/workflows/workshop.yml
- apps/sandbox/src/providers.ts
- apps/sandbox/src/utils/internal.ts
- apps/workshop/.eslintrc.js
- apps/workshop/common/utils/numbers.ts
- apps/workshop/common/utils/urls.ts
- apps/workshop/projects/SymbiosisFinance/modules/veSIS.ts
- apps/workshop/projects/WhiteWhale/helpers/calculation.ts
- apps/workshop/projects/WhiteWhale/helpers/config.ts
- apps/workshop/projects/WhiteWhale/helpers/index.ts
- apps/workshop/projects/WhiteWhale/helpers/types.ts
- apps/workshop/projects/WhiteWhale/index.ts
- apps/workshop/projects/WhiteWhale/modules/WhiteWhaleLiquidity.ts
- package.json
- **Project Name**: WhiteWhale
- **Project Website**: https://app.whitewhale.money/
- **Description**: added new chain 
> feat(white-whale): added new terra-2 chain

- apps/workshop/projects/XYFinance/tests/xy.spec.ts
> fix: Remove test

- README.md
- apps/sandbox/config.ts
- apps/sandbox/src/providers.ts
- apps/sandbox/src/types/module.ts
- apps/sandbox/src/utils/internal.ts
Init zkSync Era chain in self integrations
> feat(chain): add zksync era

- .gitignore
- apps/sandbox/src/types/module.ts
- apps/workshop/common/constants/tezos.constants.ts
- apps/workshop/projects/KordFi/helpers/constants.ts
- apps/workshop/projects/KordFi/helpers/provider.ts
- apps/workshop/projects/KordFi/index.ts
- apps/workshop/projects/KordFi/modules/KordFiLending.ts
- apps/workshop/projects/KordFi/modules/KordFiLeverageFarming.ts
- **Project Name**: Kord.Fi
- **Project Website**: https://kord.fi
- **Description**: New Project
https://icons.de.fi/icons/studio/protocols/kord-fi.webp
Testing address: tz1VBXnyNVVZWpUDuSG19Kr5Wrb8pkdYQKGj
---
> feat(project): Kord.Fi

- apps/workshop/projects/KordFi/modules/KordFiLeverageFarming.ts
> fix(project): KordFi wrong supply amount in leverage farming

- apps/workshop/projects/SingleFinance/abis/abi.ts
- apps/workshop/projects/SingleFinance/helpers/constants.ts
- apps/workshop/projects/SingleFinance/helpers/findPoolByAddress.ts
- apps/workshop/projects/SingleFinance/helpers/findTokenByAddress.ts
- apps/workshop/projects/SingleFinance/helpers/getAllPools.ts
- apps/workshop/projects/SingleFinance/helpers/getApr.ts
- apps/workshop/projects/SingleFinance/helpers/getRewardApr.ts
- apps/workshop/projects/SingleFinance/helpers/getUserLending.ts
- apps/workshop/projects/SingleFinance/helpers/isSameAddress.ts
- apps/workshop/projects/SingleFinance/helpers/secondToYearlyInterestRate.ts
- apps/workshop/projects/SingleFinance/helpers/types.ts
- apps/workshop/projects/SingleFinance/index.ts
- apps/workshop/projects/SingleFinance/modules/LendingPools.ts
- **Project Name**: Single Finance
- **Project Website**: https://app.singlefinance.io
- **Description**: New Project
- **Logo**: link provided in project's `index.ts`
- **Other information**: add lending pools
> feat: add Single Finance lendng pools

- apps/workshop/projects/SingleFinance/abis/abi.ts
- apps/workshop/projects/SingleFinance/helpers/getFarms.ts
- apps/workshop/projects/SingleFinance/helpers/getUserPositions.ts
- apps/workshop/projects/SingleFinance/helpers/types.ts
- apps/workshop/projects/SingleFinance/index.ts
- apps/workshop/projects/SingleFinance/modules/LYF.ts
- apps/workshop/projects/SingleFinance/modules/LendingPools.ts
- **Project Name**:  Single Finance
- **Project Website**: https://app.singlefinance.io/
- **Description**: new LYF feature for Single Finance
- **Logo**: link provided in project's index.ts
- **Other information**: new LYF feature for Single Finance
> feat: add Single Finance LYF

- apps/workshop/projects/Bolide/index.ts
- apps/workshop/projects/Bolide/modules/DepositPoolsBnb.ts
- apps/workshop/projects/Bolide/modules/DepositPoolsPolygon.ts
- apps/workshop/projects/Bolide/tests/DepositPools.spec.ts
> fix(project): bolide deposit pools module initialization

- apps/sandbox/src/types/module.ts
- apps/workshop/projects/KordFi/modules/KordFiLeverageFarming.ts
- **Project Name**: Kord.Fi
- **Description**: `debtRatio` value
- **Result**: 
> feat(project): debtRatio for Kord.Fi

- apps/workshop/projects/AuraFinance/modules/StakeBalancerTokens.ts
> fix(project): AuraFinance. toString property of undefined
